---
title: "propensity models"
author: "Andre Hiwatig"
date: "2025-05-26"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Load Packages

```{r}
library(MatchIt)
library(tableone)
library(ggplot2)
library(readxl)
```

## Explore Data

```{r}
df <- read.csv("new_updated.csv") # from github
colnames(df) <- gsub("[[:punct:]]", "", colnames(df))

sum(is.na(df["GenderMale1Female2"]))

df['TarsusresectedYesNo'] <- sapply(df[['TarsusresectedYesNo']], function(x) {ifelse(x == "Y", 1, 0)})

sum(is.na(df$TissueResectedmm))

df$X %in% c(156, 157, 158)

df[df$X1eyetarsus1eyenormal == "yes", ]

# View(df)
```

### Original Dataset

```{r}
excel_sheets("MMCR Data Stats Class.xlsx")
patient_all <- read_excel("MMCR Data Stats Class.xlsx", sheet = "1999 to 2018")
primary_ou <- read_excel("MMCR Data Stats Class.xlsx", sheet = "Primary OU")
primary_excluding <- read_excel("MMCR Data Stats Class.xlsx", sheet = "Primary excluding")

# Check Rows
nrow(primary_ou)
nrow(primary_excluding)

colnames(patient_all)
colnames(primary_ou)
colnames(primary_excluding)

# primary_excluding_no_last <- primary_excluding[, 1:(ncol(primary_excluding) - 1)]
# primary_sorted <- primary_excluding_no_last[order(primary_excluding_no_last[["#"]]), ]
# identical(primary_ou, primary_excluding_no_last)

# Prepare for Merge Create Subset 
patient_all_subset <- patient_all[, c('#', 'Patient_name', 'DOB', 'Previous Surgery? (yes =1, No = 0)',
                                      'Post MMCR Surgery- ptosis?', 'Levator function', 'Sx Date')]

# Drop NA rows from dataset
primary_ou <- primary_ou[-(513:517), ]

```


### Duplicated Patient Name Rows

```{r}
# Step 1: Find names that appear more than once
dupes <- df$Patientname[duplicated(df$Patientname)]

# Step 2: Filter all rows where Patientname is one of the duplicates
df[df$Patientname %in% dupes, ]


### Remove Kenneth Low??
```


## Cj Data Cleaning

```{r}
# Read Dataset
df <- read.csv("new_updated.csv")

# Make Column Names Better
colnames(df) <- gsub("[[:punct:]]", "", colnames(df))

# Change Tarsus Ressected Column to Boolean Value
df['TarsusresectedYesNo'] <- sapply(df[['TarsusresectedYesNo']], function(x) {ifelse(x == "Y", 1, 0)})

# CHANGED: Changed Gender to Categorical: Male and Female
df['Gender'] <- sapply(df[['GenderMale1Female2']], function(x) {ifelse(x == 1, "Male", "Female")})

# Gender Imputation: Mode
get_mode <- function(x) {                       ## Helper Function
  ux <- na.omit(unique(x))
  ux[which.max(tabulate(match(x, ux)))]
}
                                                
mode_value <- get_mode(df[['Gender']])            ## Impute Gender
df$Gender[is.na(df$Gender)] <- mode_value


# Tissue Ressected Imputation: Mean
df$TissueResectedmm[is.na(df$TissueResectedmm)] <- mean(df$TissueResectedmm, na.rm = TRUE)

# Exclude Patients with Surgeries in both eyes
df <- df[!(df$X %in% c(156, 157, 158)), ]

head(df)
```

### Explore Age to make cutoffs

```{r}
summary(df$Age)
# hist(df$Age, breaks = 20, main = "Age Distribution", xlab = "Age")
# boxplot(df$Age, main = "Boxplot of Age", horizontal = TRUE)
# ```
# ```{r}
# df$age_group <- cut(df$Age, breaks = 3, labels = c("Young", "Middle-aged", "Older"))
# table(df$age_group)

df$age_group <- cut(df$Age,
                    breaks = c(0, 50, 70, Inf),
                    labels = c("Young", "Middle-aged", "Older"))

table(df$age_group)

```


## Cj Propensity Models

### Propensity Models (Ratio 1:1)

```{r}
## Method = "nearest"

# only included vars. with complete data 
# match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + Age + Gender + ODOS + TissueResectedmm, 
#                        data = df,
#                        method = "nearest",     
#                        ratio = 1)              

match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + ODOS + age_group, 
                       data = df,
                       method = "nearest",     
                       ratio = 1)            

summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data[matched_data['subclass'] == 1, ] # example

# Nonparametric Test: Wilcox test
wilcox.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)
wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1, paired = TRUE)


```

```{r}
## Method = "optimal"

# only included vars. with complete data 
match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + age_group + ODOS, 
                       data = df,
                       method = "optimal",     
                       ratio = 1)              
summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data[matched_data['subclass'] == 1, ] # example

treated <- matched_data[matched_data$TarsusresectedYesNo == 1, ]
control <- matched_data[matched_data$TarsusresectedYesNo == 0, ]
paired_data <- merge(treated, control, by = "subclass", suffixes = c("_treated", "_control"))


# # Nonparametric Test: Wilcox test
# wilcox.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)
# wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1, paired = TRUE)

# Unpaired
wilcox.test(paired_data$MostrecentPostOpMRD1_treated, paired_data$MostrecentPostOpMRD1_control)

# Paired
wilcox.test(paired_data$MostrecentPostOpMRD1_treated, paired_data$MostrecentPostOpMRD1_control, paired = TRUE)
```
Lower p-value of 0.3532 with method = "optimal"

```{r}
## Method = "genetic"

# only included vars. with complete data 
match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + Age + Gender + ODOS + TissueResectedmm, 
                       data = df,
                       method = "exact",     
                       ratio = 1)              
summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data[matched_data['subclass'] == 1, ] # example

# Nonparametric Test: Wilcox test
wilcox.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)
wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1, paired = TRUE)


```




## Cj Propensity Matching

```{r}
# Method argument = "optimal"
match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + Age + GenderMale1Female2 + 
                                              ODOS + TissueResectedmm, 
                       data = df,
                       method = "optimal",     
                       ratio = 1)              
summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data

boxplot(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)
t.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)

plot(matched_data, type = "density")

```







## Andre Data Cleaning
```{r}
df <- read.csv("new_updated.csv") # from github

# simplify colnames
colnames(df) <- gsub("[[:punct:]]", "", colnames(df))

# change resp var to binary for matching 
df['TarsusresectedYesNo'] <- sapply(df[['TarsusresectedYesNo']], function(x) {ifelse(x == "Y", 1, 0)})

# impute gender by mode
get_mode <- function(x) {
  ux <- na.omit(unique(x))
  ux[which.max(tabulate(match(x, ux)))]
}

mode_value <- get_mode(df[['GenderMale1Female2']])
df$GenderMale1Female2[is.na(df$GenderMale1Female2)] <- mode_value

# impute tissueresected by mean
df$TissueResectedmm[is.na(df$TissueResectedmm)] <- mean(df$TissueResectedmm, na.rm = TRUE)

# for patients with surgery in two eyes, remove the non-tarsectomy
df <- df[!(df$X %in% c(156, 157, 158)), ]

head(df)
```





#1: Andre Propensity Matching (Ratio 1:1)
```{r}
# only included vars. with complete data 
match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + Age + GenderMale1Female2 + ODOS + TissueResectedmm, 
                       data = df,
                       method = "nearest",     
                       ratio = 1)              
summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data[matched_data['subclass'] == 1, ] # example

# balance covariates
plot(match_model, type = "density", interactive = FALSE,
     which.xs = ~ PreopMRD1 + Age + GenderMale1Female2 + ODOS + TissueResectedmm)
summary(match_model)


# boxplot for postopmrd1
boxplot(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data,
        main = "Post-op MRD1 by Tarsectomy with Propensity Score Matching",
        xlab = "Tarsectomy (0 = No, 1 = Yes)",
        ylab = "Post-op MRD1 (mm)",
        col = c("skyblue", "salmon"),
        border = "gray40")

# plot of differences
ggplot(matched_data, aes(x = factor(subclass), y = MostrecentPostOpMRD1, color = factor(TarsusresectedYesNo), group = subclass)) +
  geom_point(size = 2) +
  geom_line() +
  labs(x = "Matched Pair", y = "Post-Op MRD1", color = "Group") +
  scale_color_manual(values = c("blue", "red"), labels = c("Control", "Treatment")) +
  theme_minimal() +
  theme(axis.text.x = element_blank())
```

Parametric Tests
```{r}
# Unpaired T-Test
t.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)

# Paired T-Test
treated <- matched_data[matched_data$TarsusresectedYesNo == 1, ]
control <- matched_data[matched_data$TarsusresectedYesNo == 0, ]
paired_data <- merge(treated, control, by = "subclass", suffixes = c("_treated", "_control"))
t.test(paired_data$MostrecentPostOpMRD1_treated, paired_data$MostrecentPostOpMRD1_control, paired = TRUE)

```

Nonparametric Tests
```{r}
# Unpaired
wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1)

# Paired
wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1, paired = TRUE)
```

#2: Propensity Matching (Ratio 1:2)

```{r}
# only included vars. with complete data 
match_model <- matchit(TarsusresectedYesNo ~ PreopMRD1 + Age + GenderMale1Female2 + ODOS + TissueResectedmm, 
                       data = df,
                       method = "nearest",     
                       ratio = 2)              
summary(match_model)

# matched dataset
matched_data <- match.data(match_model)
matched_data[matched_data['subclass'] == 1, ] # example

# balance covariates
plot(match_model, type = "density", interactive = FALSE,
     which.xs = ~ PreopMRD1 + Age + GenderMale1Female2 + ODOS + TissueResectedmm)
summary(match_model)

# boxplot for postopmrd1
boxplot(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data,
        main = "Post-op MRD1 by Tarsectomy with Propensity Score Matching",
        xlab = "Tarsectomy (0 = No, 1 = Yes)",
        ylab = "Post-op MRD1 (mm)",
        col = c("skyblue", "salmon"),
        border = "gray40")

# plot of differences
ggplot(matched_data, aes(x = factor(subclass), y = MostrecentPostOpMRD1, color = factor(TarsusresectedYesNo), group = subclass)) +
  geom_point(size = 2) +
  geom_line() +
  labs(x = "Matched Pair", y = "Post-Op MRD1", color = "Group") +
  scale_color_manual(values = c("blue", "red"), labels = c("Control", "Treatment")) +
  theme_minimal() +
  theme(axis.text.x = element_blank())
```

Tests
```{r}
# Unpaired T-Test (Parametric)
t.test(MostrecentPostOpMRD1 ~ TarsusresectedYesNo, data = matched_data)

# Unpaired (Nonparametric)
wilcox.test(treated$MostrecentPostOpMRD1, control$MostrecentPostOpMRD1)
```

